CRAETE TABLE STUDENT(
   STDID INT,
   STDNAME VARCHAR(15),
   STDBRANCH VARCHAR(8), 
   STDAGE INT,
   STDEMAIL VARCHAR(100));
INSERT INTO STUDENT VALUES(515,'SNEHA','CSE',18,'SNEHA@GMAIL.COM');
INSERT INTO STUDENT VALUES(516,'ESWARI','CIVIL',19,'ESWARI@GMAIL.COM');
INSERT INTO STUDENT VALUES(517,'PAVANI','IT',17,'PAVANI@GMAIL.COM');
INSERT INTO STUDENT VALUES(518,'TEJA','AI',18,'TEJA@GMAIL.COM');
INSERT INTO STUDENT VALUES(519,'AKKI','ECE',19,'AKKI@GMAIL.COM');
INSERT INTO STUDENT VALUES(520,'BHUMIKA','CAD',18,'BHUMIKA@GMAIL.COM');
SELECT *FROM STUDENT;
